-------------------------------------------------------------------------------
-- CATÁLOGOS
-------------------------------------------------------------------------------
CREATE TABLE cat_genero (
  id_genero NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(20) UNIQUE NOT NULL
);

CREATE TABLE cat_pais (
  id_pais NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pais VARCHAR2(20) UNIQUE NOT NULL
);

CREATE TABLE cat_estado (
  id_estado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado VARCHAR2(20) UNIQUE NOT NULL,
  id_pais NUMBER NOT NULL,
  CONSTRAINT fk_pais FOREIGN KEY (id_pais) REFERENCES cat_pais(id_pais)
);

CREATE TABLE cat_municipio (
  id_municipio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  municipio VARCHAR2(20) UNIQUE NOT NULL,
  id_estado NUMBER NOT NULL,
  CONSTRAINT fk_estdado FOREIGN KEY (id_estado) REFERENCES cat_estado(id_estado)
);

CREATE TABLE cat_ciudad (
  id_ciudad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) UNIQUE NOT NULL,
  id_municipio NUMBER NOT NULL,
  CONSTRAINT fk_municipio FOREIGN KEY (id_municipio) REFERENCES cat_municipio(id_municipio)
);

CREATE TABLE cat_estado_civil (
  id_estado_civil NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(30) UNIQUE NOT NULL
);

CREATE TABLE cat_nivel_programa (
  id_nivel NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(30) UNIQUE NOT NULL
);

CREATE TABLE cat_facultad (
  id_facultad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE cat_año (
  id_año NUMBER(4) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion NUMBER UNIQUE NOT NULL
);

CREATE TABLE cat_convocatoria (
  id_convocatoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(30) UNIQUE NOT NULL,
  id_año NUMBER NOT NULL,
  CONSTRAINT fk_año FOREIGN KEY (id_año) REFERENCES cat_año(id_año)
);

CREATE TABLE cat_resultado_post (
  id_resultado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(30) UNIQUE NOT NULL
);

CREATE TABLE cat_tipo_documento (
  id_tipo_documento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE cat_estado_documento (
  id_estado_documento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(30) UNIQUE NOT NULL
);

CREATE TABLE cat_concepto_pago (
  id_concepto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE cat_estado_pago (
  id_estado_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(30) UNIQUE NOT NULL
);

CREATE TABLE cat_estado_inscripcion (
  id_estado_inscripcion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(30) UNIQUE NOT NULL
);

CREATE TABLE cat_rol_usuario (
  id_rol NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(30) UNIQUE NOT NULL
);

CREATE TABLE parentezco(
  id_parientes NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parentezco  VARCHAR2(30) UNIQUE NOT NULL
);

CREATE TABLE cat_tipo_direccion (
  id_tipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE cat_clave (
  id_clave NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR2(10) UNIQUE NOT NULL
);

-------------------------------------------------------------------------------
-- ENTIDADES PRINCIPALES
-------------------------------------------------------------------------------
CREATE TABLE aspirante (
  id_aspirante NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(50) NOT NULL,
  apellido_paterno VARCHAR2(50),
  apellido_materno VARCHAR2(50),
  fecha_nacimiento DATE NOT NULL,
  curp VARCHAR2(18) NOT NULL,
  correo_electronico VARCHAR2(100) NOT NULL,
  telefono VARCHAR2(20),
  id_genero NUMBER NOT NULL,
  id_estado_civil NUMBER NOT NULL,
  id_convocatoria NUMBER NOT NULL,
  id_clave NUMBER NOT NULL;
  CONSTRAINT uq_asp_curp UNIQUE (curp),
  CONSTRAINT uq_asp_correo UNIQUE (correo_electronico),
  CONSTRAINT uk_clave UNIQUE (id_clave),
  CONSTRAINT fk_asp_genero FOREIGN KEY (id_genero) REFERENCES cat_genero(id_genero),
  CONSTRAINT fk_asp_convocatoria FOREIGN KEY (id_convocatoria) REFERENCES cat_convocatoria(id_convocatoria),
  CONSTRAINT fk_asp_clave FOREIGN KEY (id_clave) REFERENCES cat_clave(id_clave),
  CONSTRAINT fk_asp_ec FOREIGN KEY (id_estado_civil) REFERENCES cat_estado_civil(id_estado_civil),
  CONSTRAINT uk_verificacion1 UNIQUE (correo_electronico, id_convocatoria),
  CONSTRAINT uk_verificacion2 UNIQUE (id_clave, id_convocatoria),
  CONSTRAINT uk_verificacion3 UNIQUE (curp, id_convocatoria)
);

CREATE TABLE tutor (
  id_aspirante NUMBER NOT NULL UNIQUE,
  nombre VARCHAR2(50) NOT NULL,
  apellido_paterno VARCHAR2(50),
  apellido_materno VARCHAR2(50),
  correo_electronico VARCHAR2(100) NOT NULL,
  telefono VARCHAR2(20),
  id_parientes NUMBER NOT NULL,
  CONSTRAINT uq_tutor_correo UNIQUE (correo_electronico),
  CONSTRAINT fk_tutor_asp FOREIGN KEY (id_aspirante) REFERENCES aspirante(id_aspirante),
  CONSTRAINT fk_tutor_parientes FOREIGN KEY (id_parientes) REFERENCES parientezco(id_parientes)
);

CREATE TABLE direcciones (
  id_direccion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_aspirante NUMBER NOT NULL,
  calle VARCHAR2(200),
  colonia VARCHAR2(100),
  codigo_postal VARCHAR2(10),
  numero_exterior NUMBER,
  numero_interior VARCHAR2(10),
  id_pais NUMBER NOT NULL,
  id_ciudad NUMBER,
  id_tipo NUMBER,
  CONSTRAINT fk_dir_asp FOREIGN KEY (id_aspirante) REFERENCES aspirante(id_aspirante),
  CONSTRAINT fk_dir_pais FOREIGN KEY (id_pais) REFERENCES cat_pais(id_pais),
  CONSTRAINT fk_dir_ciudad FOREIGN KEY (id_ciudad) REFERENCES cat_ciudad(id_ciudad),
  CONSTRAINT fk_dir_tipo FOREIGN KEY (id_tipo) REFERENCES cat_tipo_direccion(id_tipo)
);

CREATE TABLE programa_academico (
  id_programa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_programa VARCHAR2(100) NOT NULL,
  id_nivel NUMBER NOT NULL,
  id_facultad NUMBER NOT NULL,
  CONSTRAINT fk_prog_nivel FOREIGN KEY (id_nivel) REFERENCES cat_nivel_programa(id_nivel),
  CONSTRAINT fk_prog_fac FOREIGN KEY (id_facultad) REFERENCES cat_facultad(id_facultad)
);

CREATE TABLE proceso_seleccion (
  id_proceso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_programa NUMBER NOT NULL,
  id_año NUMBER(4) NOT NULL,
  id_convocatoria NUMBER NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  CONSTRAINT fk_proc_prog FOREIGN KEY (id_programa) REFERENCES programa_academico(id_programa),
  CONSTRAINT fk_año FOREIGN KEY (id_año) REFERENCES cat_año(id_año),
  CONSTRAINT fk_proc_conv FOREIGN KEY (id_convocatoria) REFERENCES cat_convocatoria(id_convocatoria),
  CONSTRAINT uq_proc UNIQUE (id_programa, anio, id_convocatoria)
);

CREATE TABLE postulacion (
  id_postulacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_aspirante NUMBER NOT NULL,
  id_proceso NUMBER NOT NULL,
  fecha_registro DATE DEFAULT SYSDATE NOT NULL,
  id_resultado NUMBER NOT NULL,
  CONSTRAINT fk_post_asp FOREIGN KEY (id_aspirante) REFERENCES aspirante(id_aspirante),
  CONSTRAINT fk_post_proc FOREIGN KEY (id_proceso) REFERENCES proceso_seleccion(id_proceso),
  CONSTRAINT fk_post_res FOREIGN KEY (id_resultado) REFERENCES cat_resultado_post(id_resultado),
  CONSTRAINT uq_post UNIQUE (id_aspirante, id_proceso)
);

CREATE TABLE evaluacion (
  id_evaluacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_postulacion NUMBER NOT NULL,
  examen NUMBER(5,2),
  entrevista NUMBER(5,2),
  promedio_final NUMBER(5,2),
  observaciones VARCHAR2(200),
  CONSTRAINT fk_eval_post FOREIGN KEY (id_postulacion) REFERENCES postulacion(id_postulacion),
  CONSTRAINT uq_eval_post UNIQUE (id_postulacion)
);

CREATE TABLE admision (
  id_admision NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_postulacion NUMBER NOT NULL,
  fecha_admision DATE NOT NULL,
  CONSTRAINT fk_adm_post FOREIGN KEY (id_postulacion) REFERENCES postulacion(id_postulacion),
  CONSTRAINT uq_adm_post UNIQUE (id_postulacion)
);

CREATE TABLE inscripcion (
  id_inscripcion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_admision NUMBER NOT NULL,
  fecha_inscripcion DATE NOT NULL,
  id_estado_inscripcion NUMBER NOT NULL,
  CONSTRAINT fk_ins_adm FOREIGN KEY (id_admision) REFERENCES admision(id_admision),
  CONSTRAINT fk_ins_estado FOREIGN KEY (id_estado_inscripcion) REFERENCES cat_estado_inscripcion(id_estado_inscripcion),
  CONSTRAINT uq_ins_adm UNIQUE (id_admision)
);

CREATE TABLE documento (
  id_documento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_aspirante NUMBER NOT NULL,
  id_tipo_documento NUMBER NOT NULL,
  url_archivo VARCHAR2(200) NOT NULL,
  id_estado_documento NUMBER NOT NULL,
  fecha_carga DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_doc_asp FOREIGN KEY (id_aspirante) REFERENCES aspirante(id_aspirante),
  CONSTRAINT fk_doc_tipo FOREIGN KEY (id_tipo_documento) REFERENCES cat_tipo_documento(id_tipo_documento),
  CONSTRAINT fk_doc_estado FOREIGN KEY (id_estado_documento) REFERENCES cat_estado_documento(id_estado_documento)
);

CREATE TABLE pago (
  id_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_postulacion NUMBER NOT NULL,
  id_concepto NUMBER NOT NULL,
  monto NUMBER(10,2) NOT NULL,
  fecha_pago DATE NOT NULL,
  id_estado_pago NUMBER NOT NULL,
  referencia VARCHAR2(100),
  CONSTRAINT fk_pago_post FOREIGN KEY (id_postulacion) REFERENCES postulacion(id_postulacion),
  CONSTRAINT fk_pago_concepto FOREIGN KEY (id_concepto) REFERENCES cat_concepto_pago(id_concepto),
  CONSTRAINT fk_pago_estado FOREIGN KEY (id_estado_pago) REFERENCES cat_estado_pago(id_estado_pago)
);

CREATE TABLE usuario_sistema (
  id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(50) NOT NULL,
  correo VARCHAR2(100) NOT NULL,
  contrasena VARCHAR2(200) NOT NULL,
  id_rol NUMBER NOT NULL,
  CONSTRAINT uq_user_correo UNIQUE (correo),
  CONSTRAINT fk_user_rol FOREIGN KEY (id_rol) REFERENCES cat_rol_usuario(id_rol)
);